# Generated by Django 4.2.3 on 2023-08-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('information', 'Information'), ('sales', 'About Sales'), ('payment', 'About Payment'), ('schedule', 'About Schedule')], max_length=50, verbose_name='Topic')),
                ('status', models.CharField(blank=True, choices=[('read', 'Read'), ('unread', 'unread')], default='unread', max_length=6, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='property.property')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inquiry.inquiry')),
            ],
            options={
                'verbose_name': 'Inquiry reply',
                'verbose_name_plural': 'Inquiry replies',
            },
        ),
    ]
