# Generated by Django 4.2.3 on 2023-08-07 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_alter_inquiry_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='type',
            field=models.CharField(choices=[('Information', 'Information'), ('About Sales', 'About Sales'), ('About Payment', 'About Payment'), ('About Schedule', 'About Schedule')], default=django.utils.timezone.now, max_length=30, verbose_name='Topic'),
            preserve_default=False,
        ),
    ]
