# Generated by Django 4.2.3 on 2023-08-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_inquiry_status_alter_inquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
