# Generated by Django 4.2.3 on 2023-08-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0007_inquiryreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiryreply',
            options={'verbose_name': 'Inquiry reply', 'verbose_name_plural': 'Inquiry replies'},
        ),
        migrations.AlterField(
            model_name='inquiryreply',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inquiry.inquiry'),
        ),
    ]
