# Generated by Django 4.2.3 on 2023-08-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
