# Generated by Django 4.2.3 on 2023-08-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_price'),
        ('account', '0003_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='property.property'),
        ),
    ]
