# Generated by Django 4.2.3 on 2023-08-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_description'),
        ('account', '0005_alter_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='user_properties', to='property.property'),
        ),
    ]
