# Generated by Django 4.2.3 on 2023-08-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_description'),
        ('account', '0006_user_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='agent', to='property.property'),
        ),
    ]
