# Generated by Django 4.2.3 on 2023-08-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='properties',
        ),
    ]
