# Generated by Django 4.2.3 on 2023-08-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
