# Generated by Django 4.2.3 on 2023-08-21 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Deal Type',
                'verbose_name_plural': 'Deal Types',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('tazkira', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, default='---', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_deals', to=settings.AUTH_USER_MODEL)),
                ('deal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', to='deal.dealtype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_deals', to='property.property')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
    ]
