# Generated by Django 4.2.3 on 2023-08-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_property_created_at_property_deal_property_deal_date'),
        ('deal', '0002_dealtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', to='deal.dealtype'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_deals', to='property.property'),
        ),
    ]
