# Generated by Django 4.2.3 on 2023-08-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_deal_deal_type_alter_deal_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
