# Generated by Django 4.2.3 on 2023-08-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_alter_deal_end_date_alter_deal_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
