# Generated by Django 4.2.3 on 2023-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_deal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='phone2',
            field=models.CharField(blank=True, default='---', max_length=20, null=True),
        ),
    ]
