from django.urls import path, reverse_lazy
from django.contrib.auth.views import ( 
        LogoutView,
        PasswordResetView,
        PasswordResetDoneView,
        PasswordResetCompleteView,
        PasswordResetConfirmView,
        PasswordChangeView
        )

from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        'property/create/',
        views.PropertyCreate.as_view(),
        name='property_create'
    ),
    path(
        'property/update/<int:pk>/',
        views.PropertyUpdate.as_view(),
        name='property_update'
    ),
    path(
        'property/remove_property_image/<int:pk>/',
        views.remove_property_image,
        name='remove_property_image'
    ),
    path(
        'property/delete/<int:pk>/',
        views.PropertyDeleteView.as_view(),
        name='property_delete'
    ),
    path(
        'properties/agent/',
        views.AgentPropertyListView.as_view(),
        name='agent_property_list'
    ),
    path(
        'deals/create/<int:pk>/',
        views.DealCreateView.as_view(),
        name='deal_create'
    ),
    path(
        'deals/',
        views.DealListView.as_view(),
        name='deal_list'
    ),
    path(
        'deals/new/',
        views.DealPropertyChooseView.as_view(),
        name='deal_property_list'
    ),
    path(
        'deals/<int:pk>/',
        views.DealDetailView.as_view(),
        name='deal_detail'
    ),
    path(
        'deals/update/<int:pk>/',
        views.DealUpdateView.as_view(),
        name='deal_update'
    ),
    path(
        'bookmarks/',
        views.BookmarkView.as_view(),
        name='bookmarks'
    ),
    path(
        'bookmarks/remove_from_bookmarks/<int:pk>/',
        views.remove_from_bookmarks,
        name='remove_from_bookmarks'
    ),
    path(
        'login/',
        views.Login.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'register/',
        views.Register.as_view(),
        name='register'
    ),
    path(
        'activate/<uidb64>/<token>/',
        views.activate,
        name='activate'
    ),
    path(
        'reset/',
        PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
        name='password_reset'
    ),
    path(
        'reset/done/',
        PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm'
    ),
    path(
        'reset/complete/',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'password/change/',
        PasswordChangeView.as_view(
            template_name='registration/password_change.html'
            ),
        name='password_change'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
]