# Generated by Django 4.2.3 on 2023-08-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.propertytype')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search Criteria',
            },
        ),
    ]
