# Generated by Django 4.2.3 on 2023-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchcriteria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
