# Generated by Django 4.2.3 on 2023-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_searchcriteria_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='price_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='price_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
