# Generated by Django 4.2.3 on 2023-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_searchcriteria_price_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcriteria',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='floors',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='parking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
