# Generated by Django 4.2.3 on 2023-07-30 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
