# Generated by Django 4.2.3 on 2023-08-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='hall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
