# Generated by Django 4.2.3 on 2023-07-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property'),
        ),
    ]
