# Generated by Django 4.2.3 on 2023-08-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_basement_property_bathroom_property_bedroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
