# Generated by Django 4.2.3 on 2023-07-30 08:29

import datetime
from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_image_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default=datetime.datetime(2023, 7, 30, 8, 29, 34, 901714, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=property.models.path_generator),
        ),
    ]
