# Generated by Django 4.2.3 on 2023-08-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_bedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='marker_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
