# Generated by Django 4.2.3 on 2023-08-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(to='property.feature'),
        ),
    ]
