# Generated by Django 4.2.3 on 2023-08-16 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='deal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
