# Generated by Django 4.2.3 on 2023-08-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_property_created_at_property_deal_property_deal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
    ]
