# Generated by Django 4.2.3 on 2023-08-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_property_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
