# Generated by Django 4.2.3 on 2023-08-20 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_rename_location_property_address_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
