# Generated by Django 4.2.3 on 2023-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_propertytype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='image',
            field=models.ImageField(null=True, upload_to='property_types/'),
        ),
    ]
